using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nop.Plugin.Payments.Dpo
{
    public class DialCode
    {
        public string Name { get; set; }
        public string Code { get; set; }
    }

    public class DialCodes
    {
        private Dictionary<string, DialCode> codes;

        public DialCodes()
        {
            this.codes = new Dictionary<string, DialCode>()
            {
                { "AD", new DialCode { Name="Andorra", Code="376" } },
{ "AE", new DialCode { Name="United Arab Emirates", Code="971" } },
{ "AF", new DialCode { Name="Afghanistan", Code="93" } },
{ "AG", new DialCode { Name="Antigua & Barbuda", Code="1-268" } },
{ "AI", new DialCode { Name="Anguilla", Code="1-264" } },
{ "AL", new DialCode { Name="Albania", Code="355" } },
{ "AM", new DialCode { Name="Armenia", Code="374" } },
{ "AO", new DialCode { Name="Angola", Code="244" } },
{ "AQ", new DialCode { Name="Antarctica", Code="672" } },
{ "AR", new DialCode { Name="Argentina", Code="54" } },
{ "AS", new DialCode { Name="American Samoa", Code="1-684" } },
{ "AT", new DialCode { Name="Austria", Code="43" } },
{ "AU", new DialCode { Name="Australia", Code="61" } },
{ "AW", new DialCode { Name="Aruba", Code="297" } },
{ "AX", new DialCode { Name="Åland Islands", Code="358" } },
{ "AZ", new DialCode { Name="Azerbaijan", Code="994" } },
{ "BA", new DialCode { Name="Bosnia", Code="387" } },
{ "BB", new DialCode { Name="Barbados", Code="1-246" } },
{ "BD", new DialCode { Name="Bangladesh", Code="880" } },
{ "BE", new DialCode { Name="Belgium", Code="32" } },
{ "BF", new DialCode { Name="Burkina Faso", Code="226" } },
{ "BG", new DialCode { Name="Bulgaria", Code="359" } },
{ "BH", new DialCode { Name="Bahrain", Code="973" } },
{ "BI", new DialCode { Name="Burundi", Code="257" } },
{ "BJ", new DialCode { Name="Benin", Code="229" } },
{ "BL", new DialCode { Name="St. Barthélemy", Code="590" } },
{ "BM", new DialCode { Name="Bermuda", Code="1-441" } },
{ "BN", new DialCode { Name="Brunei", Code="673" } },
{ "BO", new DialCode { Name="Bolivia", Code="591" } },
{ "BQ", new DialCode { Name="Caribbean Netherlands", Code="599" } },
{ "BR", new DialCode { Name="Brazil", Code="55" } },
{ "BS", new DialCode { Name="Bahamas", Code="1-242" } },
{ "BT", new DialCode { Name="Bhutan", Code="975" } },
{ "BV", new DialCode { Name="Bouvet Island", Code="47" } },
{ "BW", new DialCode { Name="Botswana", Code="267" } },
{ "BY", new DialCode { Name="Belarus", Code="375" } },
{ "BZ", new DialCode { Name="Belize", Code="501" } },
{ "CA", new DialCode { Name="Canada", Code="1" } },
{ "CC", new DialCode { Name="Cocos (Keeling) Islands", Code="61" } },
{ "CD", new DialCode { Name="Congo - Kinshasa", Code="243" } },
{ "CF", new DialCode { Name="Central African Republic", Code="236" } },
{ "CG", new DialCode { Name="Congo - Brazzaville", Code="242" } },
{ "CH", new DialCode { Name="Switzerland", Code="41" } },
{ "CI", new DialCode { Name="Côte d’Ivoire", Code="225" } },
{ "CK", new DialCode { Name="Cook Islands", Code="682" } },
{ "CL", new DialCode { Name="Chile", Code="56" } },
{ "CM", new DialCode { Name="Cameroon", Code="237" } },
{ "CN", new DialCode { Name="China", Code="86" } },
{ "CO", new DialCode { Name="Colombia", Code="57" } },
{ "CR", new DialCode { Name="Costa Rica", Code="506" } },
{ "CU", new DialCode { Name="Cuba", Code="53" } },
{ "CV", new DialCode { Name="Cape Verde", Code="238" } },
{ "CW", new DialCode { Name="Curaçao", Code="599" } },
{ "CX", new DialCode { Name="Christmas Island", Code="61" } },
{ "CY", new DialCode { Name="Cyprus", Code="357" } },
{ "CZ", new DialCode { Name="Czechia", Code="420" } },
{ "DE", new DialCode { Name="Germany", Code="49" } },
{ "DJ", new DialCode { Name="Djibouti", Code="253" } },
{ "DK", new DialCode { Name="Denmark", Code="45" } },
{ "DM", new DialCode { Name="Dominica", Code="1-767" } },
{ "DO", new DialCode { Name="Dominican Republic", Code="1-809,1-829,1-849" } },
{ "DZ", new DialCode { Name="Algeria", Code="213" } },
{ "EC", new DialCode { Name="Ecuador", Code="593" } },
{ "EE", new DialCode { Name="Estonia", Code="372" } },
{ "EG", new DialCode { Name="Egypt", Code="20" } },
{ "EH", new DialCode { Name="Western Sahara", Code="212" } },
{ "ER", new DialCode { Name="Eritrea", Code="291" } },
{ "ES", new DialCode { Name="Spain", Code="34" } },
{ "ET", new DialCode { Name="Ethiopia", Code="251" } },
{ "FI", new DialCode { Name="Finland", Code="358" } },
{ "FJ", new DialCode { Name="Fiji", Code="679" } },
{ "FK", new DialCode { Name="Falkland Islands", Code="500" } },
{ "FM", new DialCode { Name="Micronesia", Code="691" } },
{ "FO", new DialCode { Name="Faroe Islands", Code="298" } },
{ "FR", new DialCode { Name="France", Code="33" } },
{ "GA", new DialCode { Name="Gabon", Code="241" } },
{ "GB", new DialCode { Name="UK", Code="44" } },
{ "GD", new DialCode { Name="Grenada", Code="1-473" } },
{ "GE", new DialCode { Name="Georgia", Code="995" } },
{ "GF", new DialCode { Name="French Guiana", Code="594" } },
{ "GG", new DialCode { Name="Guernsey", Code="44" } },
{ "GH", new DialCode { Name="Ghana", Code="233" } },
{ "GI", new DialCode { Name="Gibraltar", Code="350" } },
{ "GL", new DialCode { Name="Greenland", Code="299" } },
{ "GM", new DialCode { Name="Gambia", Code="220" } },
{ "GN", new DialCode { Name="Guinea", Code="224" } },
{ "GP", new DialCode { Name="Guadeloupe", Code="590" } },
{ "GQ", new DialCode { Name="Equatorial Guinea", Code="240" } },
{ "GR", new DialCode { Name="Greece", Code="30" } },
{ "GS", new DialCode { Name="South Georgia & South Sandwich Islands", Code="500" } },
{ "GT", new DialCode { Name="Guatemala", Code="502" } },
{ "GU", new DialCode { Name="Guam", Code="1-671" } },
{ "GW", new DialCode { Name="Guinea-Bissau", Code="245" } },
{ "GY", new DialCode { Name="Guyana", Code="592" } },
{ "HK", new DialCode { Name="Hong Kong", Code="852" } },
{ "HM", new DialCode { Name="Heard & McDonald Islands", Code="672" } },
{ "HN", new DialCode { Name="Honduras", Code="504" } },
{ "HR", new DialCode { Name="Croatia", Code="385" } },
{ "HT", new DialCode { Name="Haiti", Code="509" } },
{ "HU", new DialCode { Name="Hungary", Code="36" } },
{ "ID", new DialCode { Name="Indonesia", Code="62" } },
{ "IE", new DialCode { Name="Ireland", Code="353" } },
{ "IL", new DialCode { Name="Israel", Code="972" } },
{ "IM", new DialCode { Name="Isle of Man", Code="44" } },
{ "IN", new DialCode { Name="India", Code="91" } },
{ "IO", new DialCode { Name="British Indian Ocean Territory", Code="246" } },
{ "IQ", new DialCode { Name="Iraq", Code="964" } },
{ "IR", new DialCode { Name="Iran", Code="98" } },
{ "IS", new DialCode { Name="Iceland", Code="354" } },
{ "IT", new DialCode { Name="Italy", Code="39" } },
{ "JE", new DialCode { Name="Jersey", Code="44" } },
{ "JM", new DialCode { Name="Jamaica", Code="1-876" } },
{ "JO", new DialCode { Name="Jordan", Code="962" } },
{ "JP", new DialCode { Name="Japan", Code="81" } },
{ "KE", new DialCode { Name="Kenya", Code="254" } },
{ "KG", new DialCode { Name="Kyrgyzstan", Code="996" } },
{ "KH", new DialCode { Name="Cambodia", Code="855" } },
{ "KI", new DialCode { Name="Kiribati", Code="686" } },
{ "KM", new DialCode { Name="Comoros", Code="269" } },
{ "KN", new DialCode { Name="St. Kitts & Nevis", Code="1-869" } },
{ "KP", new DialCode { Name="North Korea", Code="850" } },
{ "KR", new DialCode { Name="South Korea", Code="82" } },
{ "KW", new DialCode { Name="Kuwait", Code="965" } },
{ "KY", new DialCode { Name="Cayman Islands", Code="1-345" } },
{ "KZ", new DialCode { Name="Kazakhstan", Code="7" } },
{ "LA", new DialCode { Name="Laos", Code="856" } },
{ "LB", new DialCode { Name="Lebanon", Code="961" } },
{ "LC", new DialCode { Name="St. Lucia", Code="1-758" } },
{ "LI", new DialCode { Name="Liechtenstein", Code="423" } },
{ "LK", new DialCode { Name="Sri Lanka", Code="94" } },
{ "LR", new DialCode { Name="Liberia", Code="231" } },
{ "LS", new DialCode { Name="Lesotho", Code="266" } },
{ "LT", new DialCode { Name="Lithuania", Code="370" } },
{ "LU", new DialCode { Name="Luxembourg", Code="352" } },
{ "LV", new DialCode { Name="Latvia", Code="371" } },
{ "LY", new DialCode { Name="Libya", Code="218" } },
{ "MA", new DialCode { Name="Morocco", Code="212" } },
{ "MC", new DialCode { Name="Monaco", Code="377" } },
{ "MD", new DialCode { Name="Moldova", Code="373" } },
{ "ME", new DialCode { Name="Montenegro", Code="382" } },
{ "MF", new DialCode { Name="St. Martin", Code="590" } },
{ "MG", new DialCode { Name="Madagascar", Code="261" } },
{ "MH", new DialCode { Name="Marshall Islands", Code="692" } },
{ "MK", new DialCode { Name="Macedonia", Code="389" } },
{ "ML", new DialCode { Name="Mali", Code="223" } },
{ "MM", new DialCode { Name="Myanmar", Code="95" } },
{ "MN", new DialCode { Name="Mongolia", Code="976" } },
{ "MO", new DialCode { Name="Macau", Code="853" } },
{ "MP", new DialCode { Name="Northern Mariana Islands", Code="1-670" } },
{ "MQ", new DialCode { Name="Martinique", Code="596" } },
{ "MR", new DialCode { Name="Mauritania", Code="222" } },
{ "MS", new DialCode { Name="Montserrat", Code="1-664" } },
{ "MT", new DialCode { Name="Malta", Code="356" } },
{ "MU", new DialCode { Name="Mauritius", Code="230" } },
{ "MV", new DialCode { Name="Maldives", Code="960" } },
{ "MW", new DialCode { Name="Malawi", Code="265" } },
{ "MX", new DialCode { Name="Mexico", Code="52" } },
{ "MY", new DialCode { Name="Malaysia", Code="60" } },
{ "MZ", new DialCode { Name="Mozambique", Code="258" } },
{ "NA", new DialCode { Name="Namibia", Code="264" } },
{ "NC", new DialCode { Name="New Caledonia", Code="687" } },
{ "NE", new DialCode { Name="Niger", Code="227" } },
{ "NF", new DialCode { Name="Norfolk Island", Code="672" } },
{ "NG", new DialCode { Name="Nigeria", Code="234" } },
{ "NI", new DialCode { Name="Nicaragua", Code="505" } },
{ "NL", new DialCode { Name="Netherlands", Code="31" } },
{ "NO", new DialCode { Name="Norway", Code="47" } },
{ "NP", new DialCode { Name="Nepal", Code="977" } },
{ "NR", new DialCode { Name="Nauru", Code="674" } },
{ "NU", new DialCode { Name="Niue", Code="683" } },
{ "NZ", new DialCode { Name="New Zealand", Code="64" } },
{ "OM", new DialCode { Name="Oman", Code="968" } },
{ "PA", new DialCode { Name="Panama", Code="507" } },
{ "PE", new DialCode { Name="Peru", Code="51" } },
{ "PF", new DialCode { Name="French Polynesia", Code="689" } },
{ "PG", new DialCode { Name="Papua New Guinea", Code="675" } },
{ "PH", new DialCode { Name="Philippines", Code="63" } },
{ "PK", new DialCode { Name="Pakistan", Code="92" } },
{ "PL", new DialCode { Name="Poland", Code="48" } },
{ "PM", new DialCode { Name="St. Pierre & Miquelon", Code="508" } },
{ "PN", new DialCode { Name="Pitcairn Islands", Code="870" } },
{ "PR", new DialCode { Name="Puerto Rico", Code="1" } },
{ "PS", new DialCode { Name="Palestine", Code="970" } },
{ "PT", new DialCode { Name="Portugal", Code="351" } },
{ "PW", new DialCode { Name="Palau", Code="680" } },
{ "PY", new DialCode { Name="Paraguay", Code="595" } },
{ "QA", new DialCode { Name="Qatar", Code="974" } },
{ "RE", new DialCode { Name="Réunion", Code="262" } },
{ "RO", new DialCode { Name="Romania", Code="40" } },
{ "RS", new DialCode { Name="Serbia", Code="381" } },
{ "RU", new DialCode { Name="Russia", Code="7" } },
{ "RW", new DialCode { Name="Rwanda", Code="250" } },
{ "SA", new DialCode { Name="Saudi Arabia", Code="966" } },
{ "SB", new DialCode { Name="Solomon Islands", Code="677" } },
{ "SC", new DialCode { Name="Seychelles", Code="248" } },
{ "SD", new DialCode { Name="Sudan", Code="249" } },
{ "SE", new DialCode { Name="Sweden", Code="46" } },
{ "SG", new DialCode { Name="Singapore", Code="65" } },
{ "SH", new DialCode { Name="St. Helena", Code="290" } },
{ "SI", new DialCode { Name="Slovenia", Code="386" } },
{ "SJ", new DialCode { Name="Svalbard & Jan Mayen", Code="47" } },
{ "SK", new DialCode { Name="Slovakia", Code="421" } },
{ "SL", new DialCode { Name="Sierra Leone", Code="232" } },
{ "SM", new DialCode { Name="San Marino", Code="378" } },
{ "SN", new DialCode { Name="Senegal", Code="221" } },
{ "SO", new DialCode { Name="Somalia", Code="252" } },
{ "SR", new DialCode { Name="Suriname", Code="597" } },
{ "SS", new DialCode { Name="South Sudan", Code="211" } },
{ "ST", new DialCode { Name="São Tomé & Príncipe", Code="239" } },
{ "SV", new DialCode { Name="El Salvador", Code="503" } },
{ "SX", new DialCode { Name="Sint Maarten", Code="1-721" } },
{ "SY", new DialCode { Name="Syria", Code="963" } },
{ "SZ", new DialCode { Name="Swaziland", Code="268" } },
{ "TC", new DialCode { Name="Turks & Caicos Islands", Code="1-649" } },
{ "TD", new DialCode { Name="Chad", Code="235" } },
{ "TF", new DialCode { Name="French Southern Territories", Code="262" } },
{ "TG", new DialCode { Name="Togo", Code="228" } },
{ "TH", new DialCode { Name="Thailand", Code="66" } },
{ "TJ", new DialCode { Name="Tajikistan", Code="992" } },
{ "TK", new DialCode { Name="Tokelau", Code="690" } },
{ "TL", new DialCode { Name="Timor-Leste", Code="670" } },
{ "TM", new DialCode { Name="Turkmenistan", Code="993" } },
{ "TN", new DialCode { Name="Tunisia", Code="216" } },
{ "TO", new DialCode { Name="Tonga", Code="676" } },
{ "TR", new DialCode { Name="Turkey", Code="90" } },
{ "TT", new DialCode { Name="Trinidad & Tobago", Code="1-868" } },
{ "TV", new DialCode { Name="Tuvalu", Code="688" } },
{ "TW", new DialCode { Name="Taiwan", Code="886" } },
{ "TZ", new DialCode { Name="Tanzania", Code="255" } },
{ "UA", new DialCode { Name="Ukraine", Code="380" } },
{ "UG", new DialCode { Name="Uganda", Code="256" } },
{ "UM", new DialCode { Name="U.S. Outlying Islands", Code="0" } },
{ "US", new DialCode { Name="US", Code="1" } },
{ "UY", new DialCode { Name="Uruguay", Code="598" } },
{ "UZ", new DialCode { Name="Uzbekistan", Code="998" } },
{ "VA", new DialCode { Name="Vatican City", Code="39-06" } },
{ "VC", new DialCode { Name="St. Vincent & Grenadines", Code="1-784" } },
{ "VE", new DialCode { Name="Venezuela", Code="58" } },
{ "VG", new DialCode { Name="British Virgin Islands", Code="1-284" } },
{ "VI", new DialCode { Name="U.S. Virgin Islands", Code="1-340" } },
{ "VN", new DialCode { Name="Vietnam", Code="84" } },
{ "VU", new DialCode { Name="Vanuatu", Code="678" } },
{ "WF", new DialCode { Name="Wallis & Futuna", Code="681" } },
{ "WS", new DialCode { Name="Samoa", Code="685" } },
{ "YE", new DialCode { Name="Yemen", Code="967" } },
{ "YT", new DialCode { Name="Mayotte", Code="262" } },
{ "ZA", new DialCode { Name="South Africa", Code="27" } },
{ "ZM", new DialCode { Name="Zambia", Code="260" } },
{ "ZW", new DialCode { Name="Zimbabwe", Code="263" } },
            };
        }

        public Dictionary<string, DialCode> Codes { get => codes; }
    }
}
